<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $app \PHY\App
     */
?>
<?php
    if (isset($js)):
        $tag = $this->tag();
        foreach ($js as $file):
            echo $tag->script->attributes($file);
        endforeach;
    endif
?>
<?php if (isset($googleAnalytics)): ?>
<script type="text/javascript">(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','<?= $googleAnalytics ?>','auto');ga('require', 'displayfeatures');ga('send','pageview');</script>
<?php endif; ?>
<script type="text/javascript">try{if(typeof console!=='undefined'&&typeof console.log!=='undefined')console.log('Generation: <?=$app->getDebugger()->profile()?>')}catch(e){}</script>