<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     * @var $js array
     * @var $css array
     * @var $xsrfId string
     * @var $title string
     * @var $author string
     * @var $googleAuthor string
     * @see \PHY\View\Head
     */
?>
<?php $tag = $this->tag()?>
<?php if(!isset($title)) $title = 'Current happenings of John Mullanaphy'?>
<?php if(!isset($description)) $description = 'Recaps of my current life which usually involves nerdy hobbies.'?>
<meta charset="utf-8">
<script type="text/javascript">if(window.location.hash.toString().match('!')){var url=window.location.hash.toString().split('!');window.location=url[1];}</script>
<title><?=$this->clean($title)?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="<?=$this->clean($description)?>">
<meta name="author" content="<?=$this->clean(isset($author)?$author:'John Mullanaphy <hi@john.mu>')?>">
<link rel="author" content="<?=$this->clean(isset($googleAuthor)?$googleAuthor:'https://plus.google.com/+JohnMullanaphy')?>">
<link rel="shortcut icon" href="/favicon.ico">
<meta property="og:site_name" content="John Mullanaphy">
<meta property="og:title" content="<?=$this->clean(isset($ogTitle)?$ogTitle:'Current happenings')?>">
<meta property="og:type" content="<?=$this->clean(isset($ogType)?$ogType:'article')?>">
<meta property="og:url" content="<?=$this->clean(isset($ogUrl)?$ogUrl:'https://john.mu'.$_SERVER['REQUEST_URI'])?>">
<meta property="og:image" content="<?=$this->clean(isset($ogImage)?$ogImage:'https://john.mu/resources/solarized/images/me.jpg')?>">
<meta property="og:description" content="<?=$this->clean($description)?>">
<meta property="article:author" content="https://www.facebook.com/mullanaphy">
<?php if(isset($xsrfId)):?><script type="text/javascript">!function(){window.xsrfId='<?=$xsrfId?>';}()</script><?php endif?>
<?php
    if(isset($js)):
        foreach ($js as $file):
            echo $tag->script->attributes($file);
        endforeach;
    endif;
    if(isset($css)):
        foreach ($css as $file):
            echo $tag->link($file);
        endforeach;
    endif
?>
<?php if (isset($googleAnalytics)): ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?= $googleAnalytics ?>', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>
<?php endif; ?>
