<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     * 
     * @var $this \PHY\View\Block
     * @var $link array
     * @see \PHY\View\Header\Menu
     */
?>
<?php if(isset($links) && $links): ?>
<ul class="nav navbar-nav pull-right"><?php
    $tag = $this->tag();
    foreach ($links as $link):
        echo $tag->li(
            $tag->helper()->url($link['title'], $this->url($link['url']), array_key_exists('attributes', $link) && array_key_exists('a', $link['attributes'])
                    ? $link['attributes']['a']
                    : null), array_key_exists('attributes', $link) && array_key_exists('li', $link['attributes'])
                ? $link['attributes']['li']
                : null
        );
    endforeach;
?>
</ul>
<?php endif?>