<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $controllerName string
     */
?>
<?php if (isset($links) && $links): ?>
    <ul class="inline-list"><?php
            $tag = $this->tag();
            foreach ($links as $link):
                $li = $tag->li($tag->helper()
                    ->url($link['title'], $this->url($link['url']), array_key_exists('attributes', $link) && array_key_exists('a', $link['attributes'])
                        ? $link['attributes']['a']
                        : null), array_key_exists('attributes', $link) && array_key_exists('li', $link['attributes'])
                    ? $link['attributes']['li']
                    : null);
                if ($controllerName === $link['url'] || $controllerName . '/' . $actionName === $link['url']):
                    $li->class('active');
                endif;
                echo $li;
            endforeach;
        ?>
    </ul>
<?php endif ?>