<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     * @var $search string
     */
?>
<form action="<?= $this->url('search') ?>" class="form-inline" method="get">
    <div class="form-group">
        <input class="form-control" name="q" placeholder="Search" type="search" value="<?= $this->clean($search) ?>"/>
    </div>
    <button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-search"></span></button>
</form>