<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="row">
    <div class="columns">
        <h1><?php if (isset($item)): ?><a href="<?= $this->url('admin/blog') ?>">
                    Blog</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->title) ?><?php else: ?>New Post<?php endif ?><?php else: ?>Blog
            <a href="<?= $this->url('admin/blog/id/0') ?>">
                    <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
        </h1>
    </div>
</div>