<div class="row">
    <div class="columns">
        <h1><?php if (isset($item)): ?><a href="<?= $this->url('admin/blog') ?>">
                    Blog</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->title) ?><?php else: ?>New Post<?php endif ?><?php else: ?>Blog
            <a href="<?= $this->url('admin/blog/id/0') ?>">
                    <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
        </h1>
    </div>
</div>