<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $item \PHY\Model\Blog
     */
?>
<form action="<?= $_SERVER['REQUEST_URI'] ?>" class="form" method="post">
    <?= $this->getXsrfIdField() ?>
    <?= $this->child('message') ?>
    <div class="form-group">
        <label for="blog-title" class="control-label">Title</label>
        <input id="blog-title" class="form-control" name="blog[title]" type="text"
               value="<?= $this->clean($item->title) ?>"/>
    </div>
    <div class="row">
        <div class="columns small-6 large-6">
            <div class="form-group">
                <label for="blog-slug" class="control-label">Slug</label>
                <input id="blog-slug" class="form-control" name="blog[slug]" type="text"
                       value="<?= $this->clean($item->slug) ?>"/>
            </div>
        </div>
        <div class="columns small-6 large-6">
            <div class="form-group">
                <label for="blog-tags" class="control-label">Tags</label>
                <input id="blog-tags" class="form-control" name="blog[tags]" type="text"
                       value="<?= $this->clean($item->tags) ?>"/>
            </div>
        </div>
    </div>
    <hr/>
    <div class="form-group">
        <label for="blog-content" class="control-label">Post</label>
        <textarea class="form-control" id="blog-content" name="blog[content]" rows="20"
                  cols="30"><?= $this->clean($item->content) ?></textarea>
        <span class="help-block">Posted are rendered with <a
                href="https://guides.github.com/features/mastering-markdown" target="_blank">Markdown</a>.</span>
    </div>
    <hr/>
    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>
</form>