<div class="row">
    <div class="columns small-6">
        <h4>Contact Me</h4>
        <form action="<?= $this->url('contact') ?>" method="post" role="form">
            <?= $this->getXsrfIdField() ?>
            <?= $this->child('contact/message') ?>
            <div class="form-group">
                <label for="contact-name" class="control-label">Your Name</label>
                <input id="contact-name" class="form-control" name="email[name]" type="text"
                       value="<?= $this->clean(isset($fields['name'])
                           ? $fields['name']
                           : '') ?>"/>
            </div>
            <div class="form-group">
                <label for="contact-email" class="control-label">Your Email</label>
                <input id="contact-email" class="form-control" name="email[email]" type="email"
                       value="<?= $this->clean(isset($fields['email'])
                           ? $fields['email']
                           : '') ?>"/>
            </div>
            <div class="form-group">
                <label for="contact-message" class="control-label">Message</label>
                <textarea id="contact-message" class="form-control" name="email[content]" rows="5"
                          cols="30"><?= $this->clean(isset($fields['content'])
                        ? $fields['content']
                        : '') ?></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-danger">Send</button>
            </div>
        </form>
    </div>
    <div class="columns small-6">
        <h4>Around The Web</h4>
        <ul>
            <li><a href="https://facebook.com/mullanaphy">facebook.com/mullanaphy</a></li>
            <li><a href="https://twitter.com/kandypants3000">twitter.com/kandypants3000</a></li>
            <li><a href="https://linkedin.com/mullanaphy" rel="nofollow">linkedin.com/mullanaphy</a></li>
            <li><a href="https://behance.net/mullanaphy" rel="nofollow">behance.net/mullanaphy</a></li>
            <li><a href="https://mullanaphy.deviantart.com" rel="nofollow">mullanaphy.deviantart.com</a></li>
        </ul>
    </div>
</div>