<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="row">
    <div class="columns medium-6">
        <h4>Contact Me</h4>

        <form action="<?= $this->url('contact') ?>" method="post" role="form">
            <?= $this->getXsrfIdField() ?>
            <?= $this->child('contact/message') ?>
            <div class="form-group">
                <label for="contact-name" class="control-label">Your Name</label>
                <input id="contact-name" class="form-control" name="email[name]" type="text"
                       value="<?= $this->clean(isset($fields['name'])
                           ? $fields['name']
                           : '') ?>"/>
            </div>
            <div class="form-group">
                <label for="contact-email" class="control-label">Your Email</label>
                <input id="contact-email" class="form-control" name="email[email]" type="email"
                       value="<?= $this->clean(isset($fields['email'])
                           ? $fields['email']
                           : '') ?>"/>
            </div>
            <div class="form-group">
                <label for="contact-message" class="control-label">Message</label>
                <textarea id="contact-message" class="form-control" name="email[content]" rows="5"
                          cols="30"><?= $this->clean(isset($fields['content'])
                        ? $fields['content']
                        : '') ?></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-danger">Send</button>
            </div>
        </form>
    </div>
    <div class="columns medium-6">
        <h4>Around The Web</h4>
        <ul>
            <li><a href="https://www.facebook.com/mullanaphy" rel="nofollow">Facebook</a></li>
            <li><a href="https://twitter.com/jodotmu" rel="nofollow">Twitter</a></li>
            <li><a href="https://www.linkedin.com/in/mullanaphy" rel="nofollow">LinkedIn</a></li>
            <li><a href="https://www.behance.net/mullanaphy" rel="nofollow">Behance</a></li>
            <li><a href="https://mullanaphy.deviantart.com/" rel="nofollow">deviantART</a></li>
        </ul>
    </div>
</div>