<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $collection \PHY\Model\Blog\Collection
     * @var $count int
     */
?>
<?php if ($count): ?>
    <?php $i = 0; ?>
    <?php foreach ($collection as $item): ?>
        <h1 class="title"><a href="<?= $this->url('blog/' . $item->slug) ?>"><?= $this->clean($item->title) ?>
                <small class="right">
                    <time
                        datetime="<?= date('Y-m-d\TH:i:sa', strtotime($item->created)) ?>"><?= date('F j, Y', strtotime($item->created)) ?></time>
                </small>
            </a>
        </h1>
        <?= \Michelf\Markdown::defaultTransform($this->clean((new \PHY\Variable\Str(ucfirst($item->content)))->toShorten(1024))) ?>
        <a href="<?= $this->url('blog/' . $item->slug) ?>">more</a>
        <?php if (++$i < $count): ?>
            <hr/>
        <?php endif ?>
    <?php endforeach ?>
    <?= $this->child('news/pagination') ?>
<?php else: ?>
    <h1>Enjoy my writings</h1>
    <p>I'll mostly be writing about programming, comics, Brazilian jiu jitsu, and any other life events as I see
        fit.</p>
    <p>Right now there's nothing here since I'm still pretty darn lazy so give me a little time.</p>
<?php endif ?>