<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     * @var $item \PHY\Model\Blog
     */
?>
<h1 class="title"><?= $this->clean($item->title) ?></h1>
<h5>
    <time
        datetime="<?= date('Y-m-d\TH:i:sa', strtotime($item->created)) ?>"><?= date('F j, Y', strtotime($item->created)) ?></time>
</h5>
<?= $content ?>
<hr/>
<ul class="pagination">
    <li><a href="<?= $this->url('') ?>">Home</a></li>
    <?php if (isset($previous)): ?>
        <li><a href="<?= $this->url('blog/' . $previous) ?>">Previous</a></li>
    <?php endif; ?>
    <?php if (isset($next)): ?>
        <li><a href="<?= $this->url('blog/' . $next) ?>">Next</a></li>
    <?php endif; ?>
</ul>