<div class="reveal-modal" id="modal" data-reveal>
    <button type="button" class="close-reveal-modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="modal-logout-label">Logout</h4>

    <p>Sure you wish to logout? If you haven't saved any edited/added info it won't be saved. Otherwise
        nothing bad will happen</p>
    <hr/>
    <a href="#" class="btn btn-default cancel-reveal-modal">Cancel</a>
    <a href="<?= $this->url('logout') ?>" type="button" class="btn btn-danger">Logout!</a>
</div>
<script type="text/javascript">/*<[!CDATA[*/!function($){$('.cancel-reveal-modal').click(function(){$('#modal').foundation('reveal','close')})}(jQuery);/*]]>*/</script>