<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="reveal-modal" id="modal" data-reveal>
    <button type="button" class="close-reveal-modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="modal-logout-label">Logout</h4>

    <p>Sure you wish to logout? If you haven't saved any edited/added info it won't be saved. Otherwise
        nothing bad will happen</p>
    <hr/>
    <a href="#" class="btn btn-default cancel-reveal-modal">Cancel</a>
    <a href="<?= $this->url('logout') ?>" type="button" class="btn btn-danger">Logout!</a>
</div>
<script type="text/javascript">/*<[!CDATA[*/
    !function($) {
        $('.cancel-reveal-modal').click(function() {
            $('#modal').foundation('reveal', 'close')
        })
    }(jQuery);
    /*]]>*/</script>