<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<!DOCTYPE html>
<html>
<head><?= $this->child('head'); ?></head>
<body class="two-column">
<?= $this->child('header') ?>
<?= $this->child('alert') ?>
<div class="row">
    <div class="columns medium-8">
        <?= $this->child('jumbotron') ?>
        <?= $this->child('content') ?>
    </div>
    <div class="columns medium-4"><?= $this->child('sidebar') ?></div>
</div>
<?= $this->child('footer') ?>
<?= $this->child('modal') ?>
</body>
</html>