<div class="row">
    <div class="columns">
        <h1><?php if (isset($item)): ?><a href="<?= $this->url('admin/config') ?>">
                    Settings</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->key) ?><?php else: ?>New Setting<?php endif ?><?php else: ?>Settings
            <a href="<?= $this->url('admin/config/id/0') ?>">
                    <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
        </h1>
    </div>
</div>