<div class="panel radius">
    <a href="<?= $this->url('') ?>"><img src="<?= $this->url('me.jpg', 'images') ?>"/></a>

    <p>Greetings! I'm John Mullanaphy and currently busy making things for <a href="">Forensiq</a>. When I'm not coding
        there then I'm usually found toying on <a href="https://github.com/">github</a> or creating comics at <a
            href="http://www.boycottpaper.com/">Boycott Paper</a>.</p>

    <p>Outside of the programming world you can probably find me on the mats at <a
            href="http://www.marcelogarciajj.com/">Marcelo Garcia Academy</a>, playing some chess,
        or creating dream houses in Minecraft.</p>

    <p>Feel free to <a href="<?= $this->url('contact') ?>" class="contact-popup">contact me</a> if you have any
        questions or requests.</p>
</div>
<p>&copy; John Mullanaphy 2014</p>