<?php
    /**
     * jo.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (http://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="panel">
    <p><a href="<?= $this->url('') ?>"><img src="<?= $this->url('me.jpg', 'images') ?>"/></a></p>

    <p>I'm John Mullanaphy and currently busy making things for <a href="http://www.forensiq.com/">Forensiq</a>. When
        I'm not coding
        there then I'm usually found toying on <a href="https://github.com/">GitHub</a> or creating comics at <a
            href="http://www.boycottpaper.com/">Boycott Paper</a>.</p>

    <p>Outside of the programming world you can probably find me on the mats at <a
            href="http://www.marcelogarciajj.com/">Marcelo Garcia Academy</a>, playing some chess,
        or creating dream houses in Minecraft.</p>

    <p>Feel free to <a href="<?= $this->url('contact') ?>" class="contact-popup">contact me</a> if you have any
        questions or requests.</p>
</div>
<div class="credits">
    <em>&copy; John Mullanaphy 2014</em><br/>
    Color theme is <a href="http://ethanschoonover.com/solarized">Solarized</a> by Ethan Schoonover, use it.
</div>