<?php
    /**
     * john.mu
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\JO
     * @copyright Copyright (c) 2014 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="panel">
  <p><a href="<?= $this->url('') ?>"><img src="<?= $this->url('me.jpg', 'images') ?>"/></a></p>
  <p>Greetings, I'm John Mullanaphy and currently creating stuff at <a href="https://www.forensiq.com/" rel="nofollow">Forensiq</a>
    as a Senior Principal Software Engineer. When I'm not coding there then I'm usually found toying around on <a
        href="https://github.jo.mu" rel="nofollow">GitHub</a> or creating comics at <a
        href="https://www.boycottpaper.com/">Boycott Paper</a>.</p>
  <p>Outside of the programming world you can probably find me on the mats rocking a purple belt at <a
        href="http://www.marcelogarciajj.com/" rel="nofollow">Marcelo Garcia Academy</a>, streaming on <a
        href="https://twitch.jo.mu" rel="nofollow">Twitch</a>, or playing some <a
        href="https://chess.jo.mu" rel="nofollow">chess</a>.</p>
  <p>Feel free to message on <a href="https://twitter.jo.mu" rel="nofollow">Twitter</a> if you have any questions or
    requests. Please help yourself to my printable <a href="<?= $this->url('resume') ?>" target="_blank">r&eacute;sum&eacute;</a>
    as well!</p>
</div>
<div class="credits">
  <ul class="no-bullet">
    <li><em>&copy; John Mullanaphy 2014-<?= date('Y') ?></em>.</li>
    <li>Portrait drawn by <a href="https://www.immortalchoke.com/" rel="nofollow">Billy Hong at ImmortalChoke</a>.</li>
    <li>Color theme is <a href="http://ethanschoonover.com/solarized" rel="nofollow">Solarized</a> by Ethan Schoonover,
      use it.
    </li>
  </ul>
</div>
