<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $User \PHY\Model\User
     */
?>
<h1><a href="<?=$this->url('admin/user')?>">Manage Users</a></h1>
<?php if ($User->id):?><h2>Editing: <?=$User->name?></h2><?php endif;?>
<form action="<?=$_SERVER['REQUEST_URI']?>" method="post">
    <?=$this->child('message')?>
    <fieldset>
        <?php foreach ($User->toArray() as $key => $value):?>
                <dl>
                    <dt><?=$this->clean(ucfirst($key))?>:</dt>
                    <dd><input name="<?=$this->clean($key)?>" type="text" value="<?=$this->clean($User->$key)?>" /></dd>
                </dl>
            <?php endforeach?>
    </fieldset>
    <fieldset class="submit">
        <input type="submit" value="Save &raquo;" />
    </fieldset>
</form>