<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="page-header">
    <h1>Please Login</h1>
</div>
<form action="<?= $this->url('login') ?>" class="form" method="post">
    <?= $this->child('error') ?>
    <div class="row">
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="login-username" class="control-label">Email</label>
                <input id="login-username" class="form-control" name="username" type="text" value="<?=
                    isset($username)
                        ? $this->clean($username)
                        : null ?>"/>
            </div>
        </div>
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="login-password" class="control-label">Password</label>
                <input id="login-password" class="form-control" name="password" type="password"/>
            </div>
        </div>
    </div>
    <hr/>
    <div class="form-group">
        <button class="btn btn-danger">Login</button>
    </div>
</form>